version: '2.1'
services:
    jupyterlab:
        build:
            context: .
            dockerfile: ./docker/jupyterlab/Dockerfile
        container_name: "jupyterlab"
        ports:
            - 8888:8888
        volumes:
            - ${BEHEMOTH_HOME:-/mnt/raid/data/behemoth}:/behemoth
            - ${USER_HOME?USER_HOME is required}:${USER_HOME}
